/*
Copyright (C) 2017, Silent Circle, LLC.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Any redistribution, use, or modification is done solely for personal
      benefit and not for any commercial purpose or for monetary gain
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name Silent Circle nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL SILENT CIRCLE, LLC BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
package com.silentcircle.messaging.util;

import android.content.Context;
import android.net.Uri;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.silentcircle.messaging.providers.AudioProvider;

public class PresentationType {
    public static final String TYPE_NONE = "";
    public static final String TYPE_SOUND_RECORDING = "sound_recording";

    @NonNull
    public static String getType(Uri uri) {
        if (uri.equals(AudioProvider.CONTENT_URI)) {
            return TYPE_SOUND_RECORDING;
        }
        return TYPE_NONE;
    }

    public static boolean isSoundRecording (String type) {
        return type != null && type.equals(TYPE_SOUND_RECORDING);
    }

    /**
     * Compatibility method for messages generated by SP versions that don't set the "Presentation
     * type" to the attachment JSON.
     *
     * In case the mime type is audio we return "true", because the attachment is probably a
     * sound recording and not an attached sound file.
     */
    public static boolean isSoundRecordingLegacy(String presentationType, String mimeType) {
        boolean isSoundRecording = false;
        if (presentationType == null) {
            if (MIME.isAudio(mimeType)) {
                isSoundRecording = true;
            }
        }
        else {
            isSoundRecording = isSoundRecording(presentationType);
        }
        return isSoundRecording;
    }
}
