/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_silentcircle_silentphone2_services_PhoneServiceNative */

#ifndef _Included_com_silentcircle_silentphone2_services_PhoneServiceNative
#define _Included_com_silentcircle_silentphone2_services_PhoneServiceNative
#ifdef __cplusplus
extern "C" {
#endif
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_OPTION
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_OPTION 1L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NO_LIST
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NO_LIST -1L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_OPEN_FAILED
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_OPEN_FAILED -2L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_DB_FAILURE
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_DB_FAILURE -3L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NO_CLASS
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NO_CLASS -4L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NO_METHOD
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NO_METHOD -5L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NOT_IMPLEMENTED
#define com_silentcircle_silentphone2_services_PhoneServiceNative_ZID_READ_NOT_IMPLEMENTED -6L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_NO_GLOBAL_REF
#define com_silentcircle_silentphone2_services_PhoneServiceNative_NO_GLOBAL_REF -1L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_NO_CLASS
#define com_silentcircle_silentphone2_services_PhoneServiceNative_NO_CLASS -2L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_NO_WAKE_UP_CALLBACK
#define com_silentcircle_silentphone2_services_PhoneServiceNative_NO_WAKE_UP_CALLBACK -3L
#undef com_silentcircle_silentphone2_services_PhoneServiceNative_NO_STATE_CALLBACK
#define com_silentcircle_silentphone2_services_PhoneServiceNative_NO_STATE_CALLBACK -4L
/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    doInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_doInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    getInfo
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_getInfo
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    setKeyData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_setKeyData
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    initPhone
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_initPhone
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    savePath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_savePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    saveImei
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_saveImei
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    checkNetState
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_checkNetState
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    doCmd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_doCmd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    getPhoneState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_getPhoneState
  (JNIEnv *, jclass);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    nv21ToRGB32
 * Signature: ([B[I[SIII)V
 */
JNIEXPORT void JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_nv21ToRGB32
  (JNIEnv *, jclass, jbyteArray, jintArray, jshortArray, jint, jint, jint);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    getVFrame
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_getVFrame
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    readAllZid
 * Signature: (Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_readAllZid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    getOptionFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_getOptionFlags
  (JNIEnv *, jclass);

/*
 * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
 * Method:    getZrtpCounters
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_getZrtpCounters
  (JNIEnv *, jclass, jint);

/*
  * Class:     com_silentcircle_silentphone2_services_PhoneServiceNative
  * Method:    setPushToken
  * Signature: (Ljava/lang/String;)I
  */
 JNIEXPORT void JNICALL Java_com_silentcircle_silentphone2_services_PhoneServiceNative_setPushToken
   (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
