// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testmessage.proto

package com.example.werner;

public final class TextMessage {
  private TextMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TextmessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.protobuf.Textmessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional sint64 longInt64 = 1;</code>
     */
    boolean hasLongInt64();
    /**
     * <code>optional sint64 longInt64 = 1;</code>
     */
    long getLongInt64();

    /**
     * <code>optional sint32 standardInt32 = 2;</code>
     */
    boolean hasStandardInt32();
    /**
     * <code>optional sint32 standardInt32 = 2;</code>
     */
    int getStandardInt32();

    /**
     * <code>optional string someText = 3;</code>
     */
    boolean hasSomeText();
    /**
     * <code>optional string someText = 3;</code>
     */
    java.lang.String getSomeText();
    /**
     * <code>optional string someText = 3;</code>
     */
    com.google.protobuf.ByteString
        getSomeTextBytes();
  }
  /**
   * Protobuf type {@code test.protobuf.Textmessage}
   */
  public static final class Textmessage extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:test.protobuf.Textmessage)
      TextmessageOrBuilder {
    // Use Textmessage.newBuilder() to construct.
    private Textmessage(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Textmessage(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final Textmessage defaultInstance;
    public static Textmessage getDefaultInstance() {
      return defaultInstance;
    }

    public Textmessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private Textmessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              longInt64_ = input.readSInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              standardInt32_ = input.readSInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              someText_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Textmessage> PARSER =
        new com.google.protobuf.AbstractParser<Textmessage>() {
      public Textmessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Textmessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Textmessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LONGINT64_FIELD_NUMBER = 1;
    private long longInt64_;
    /**
     * <code>optional sint64 longInt64 = 1;</code>
     */
    public boolean hasLongInt64() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional sint64 longInt64 = 1;</code>
     */
    public long getLongInt64() {
      return longInt64_;
    }

    public static final int STANDARDINT32_FIELD_NUMBER = 2;
    private int standardInt32_;
    /**
     * <code>optional sint32 standardInt32 = 2;</code>
     */
    public boolean hasStandardInt32() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint32 standardInt32 = 2;</code>
     */
    public int getStandardInt32() {
      return standardInt32_;
    }

    public static final int SOMETEXT_FIELD_NUMBER = 3;
    private java.lang.Object someText_;
    /**
     * <code>optional string someText = 3;</code>
     */
    public boolean hasSomeText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string someText = 3;</code>
     */
    public java.lang.String getSomeText() {
      java.lang.Object ref = someText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          someText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string someText = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSomeTextBytes() {
      java.lang.Object ref = someText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        someText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      longInt64_ = 0L;
      standardInt32_ = 0;
      someText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, longInt64_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, standardInt32_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSomeTextBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, longInt64_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, standardInt32_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSomeTextBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.werner.TextMessage.Textmessage)) {
        return super.equals(obj);
      }
      com.example.werner.TextMessage.Textmessage other = (com.example.werner.TextMessage.Textmessage) obj;

      boolean result = true;
      result = result && (hasLongInt64() == other.hasLongInt64());
      if (hasLongInt64()) {
        result = result && (getLongInt64()
            == other.getLongInt64());
      }
      result = result && (hasStandardInt32() == other.hasStandardInt32());
      if (hasStandardInt32()) {
        result = result && (getStandardInt32()
            == other.getStandardInt32());
      }
      result = result && (hasSomeText() == other.hasSomeText());
      if (hasSomeText()) {
        result = result && getSomeText()
            .equals(other.getSomeText());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + com.example.werner.TextMessage.Textmessage.class.hashCode();
      if (hasLongInt64()) {
        hash = (37 * hash) + LONGINT64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLongInt64());
      }
      if (hasStandardInt32()) {
        hash = (37 * hash) + STANDARDINT32_FIELD_NUMBER;
        hash = (53 * hash) + getStandardInt32();
      }
      if (hasSomeText()) {
        hash = (37 * hash) + SOMETEXT_FIELD_NUMBER;
        hash = (53 * hash) + getSomeText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.werner.TextMessage.Textmessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.werner.TextMessage.Textmessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.werner.TextMessage.Textmessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.werner.TextMessage.Textmessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.werner.TextMessage.Textmessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code test.protobuf.Textmessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.werner.TextMessage.Textmessage, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:test.protobuf.Textmessage)
        com.example.werner.TextMessage.TextmessageOrBuilder {
      // Construct using com.example.werner.TextMessage.Textmessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        longInt64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        standardInt32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        someText_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.example.werner.TextMessage.Textmessage getDefaultInstanceForType() {
        return com.example.werner.TextMessage.Textmessage.getDefaultInstance();
      }

      public com.example.werner.TextMessage.Textmessage build() {
        com.example.werner.TextMessage.Textmessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.werner.TextMessage.Textmessage buildPartial() {
        com.example.werner.TextMessage.Textmessage result = new com.example.werner.TextMessage.Textmessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longInt64_ = longInt64_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.standardInt32_ = standardInt32_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.someText_ = someText_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.example.werner.TextMessage.Textmessage other) {
        if (other == com.example.werner.TextMessage.Textmessage.getDefaultInstance()) return this;
        if (other.hasLongInt64()) {
          setLongInt64(other.getLongInt64());
        }
        if (other.hasStandardInt32()) {
          setStandardInt32(other.getStandardInt32());
        }
        if (other.hasSomeText()) {
          bitField0_ |= 0x00000004;
          someText_ = other.someText_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.werner.TextMessage.Textmessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.werner.TextMessage.Textmessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long longInt64_ ;
      /**
       * <code>optional sint64 longInt64 = 1;</code>
       */
      public boolean hasLongInt64() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional sint64 longInt64 = 1;</code>
       */
      public long getLongInt64() {
        return longInt64_;
      }
      /**
       * <code>optional sint64 longInt64 = 1;</code>
       */
      public Builder setLongInt64(long value) {
        bitField0_ |= 0x00000001;
        longInt64_ = value;
        
        return this;
      }
      /**
       * <code>optional sint64 longInt64 = 1;</code>
       */
      public Builder clearLongInt64() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longInt64_ = 0L;
        
        return this;
      }

      private int standardInt32_ ;
      /**
       * <code>optional sint32 standardInt32 = 2;</code>
       */
      public boolean hasStandardInt32() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint32 standardInt32 = 2;</code>
       */
      public int getStandardInt32() {
        return standardInt32_;
      }
      /**
       * <code>optional sint32 standardInt32 = 2;</code>
       */
      public Builder setStandardInt32(int value) {
        bitField0_ |= 0x00000002;
        standardInt32_ = value;
        
        return this;
      }
      /**
       * <code>optional sint32 standardInt32 = 2;</code>
       */
      public Builder clearStandardInt32() {
        bitField0_ = (bitField0_ & ~0x00000002);
        standardInt32_ = 0;
        
        return this;
      }

      private java.lang.Object someText_ = "";
      /**
       * <code>optional string someText = 3;</code>
       */
      public boolean hasSomeText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string someText = 3;</code>
       */
      public java.lang.String getSomeText() {
        java.lang.Object ref = someText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            someText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string someText = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSomeTextBytes() {
        java.lang.Object ref = someText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string someText = 3;</code>
       */
      public Builder setSomeText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        someText_ = value;
        
        return this;
      }
      /**
       * <code>optional string someText = 3;</code>
       */
      public Builder clearSomeText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        someText_ = getDefaultInstance().getSomeText();
        
        return this;
      }
      /**
       * <code>optional string someText = 3;</code>
       */
      public Builder setSomeTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        someText_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.protobuf.Textmessage)
    }

    static {
      defaultInstance = new Textmessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.protobuf.Textmessage)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
