/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_werner_NativeTester */

#ifndef _Included_com_example_werner_NativeTester
#define _Included_com_example_werner_NativeTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_werner_NativeTester
 * Method:    testProtoBuffer
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_werner_NativeTester_testProtoBuffer
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
