// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testmessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "testmessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace test {
namespace protobuf {

void protobuf_ShutdownFile_testmessage_2eproto() {
  delete Textmessage::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_testmessage_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_testmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  Textmessage::default_instance_ = new Textmessage();
  Textmessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_testmessage_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_testmessage_2eproto_once_);
void protobuf_AddDesc_testmessage_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_testmessage_2eproto_once_,
                 &protobuf_AddDesc_testmessage_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_testmessage_2eproto {
  StaticDescriptorInitializer_testmessage_2eproto() {
    protobuf_AddDesc_testmessage_2eproto();
  }
} static_descriptor_initializer_testmessage_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int Textmessage::kLongInt64FieldNumber;
const int Textmessage::kStandardInt32FieldNumber;
const int Textmessage::kSomeTextFieldNumber;
#endif  // !_MSC_VER

Textmessage::Textmessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.protobuf.Textmessage)
}

void Textmessage::InitAsDefaultInstance() {
}

Textmessage::Textmessage(const Textmessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:test.protobuf.Textmessage)
}

void Textmessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  longint64_ = GOOGLE_LONGLONG(0);
  standardint32_ = 0;
  sometext_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Textmessage::~Textmessage() {
  // @@protoc_insertion_point(destructor:test.protobuf.Textmessage)
  SharedDtor();
}

void Textmessage::SharedDtor() {
  if (sometext_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sometext_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Textmessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Textmessage& Textmessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_testmessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_testmessage_2eproto();
#endif
  return *default_instance_;
}

Textmessage* Textmessage::default_instance_ = NULL;

Textmessage* Textmessage::New() const {
  return new Textmessage;
}

void Textmessage::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    longint64_ = GOOGLE_LONGLONG(0);
    standardint32_ = 0;
    if (has_sometext()) {
      if (sometext_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        sometext_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool Textmessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:test.protobuf.Textmessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional sint64 longInt64 = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &longint64_)));
          set_has_longint64();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_standardInt32;
        break;
      }

      // optional sint32 standardInt32 = 2;
      case 2: {
        if (tag == 16) {
         parse_standardInt32:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &standardint32_)));
          set_has_standardint32();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_someText;
        break;
      }

      // optional string someText = 3;
      case 3: {
        if (tag == 26) {
         parse_someText:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sometext()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.protobuf.Textmessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.protobuf.Textmessage)
  return false;
#undef DO_
}

void Textmessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.protobuf.Textmessage)
  // optional sint64 longInt64 = 1;
  if (has_longint64()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(1, this->longint64(), output);
  }

  // optional sint32 standardInt32 = 2;
  if (has_standardint32()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->standardint32(), output);
  }

  // optional string someText = 3;
  if (has_sometext()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sometext(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:test.protobuf.Textmessage)
}

int Textmessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional sint64 longInt64 = 1;
    if (has_longint64()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt64Size(
          this->longint64());
    }

    // optional sint32 standardInt32 = 2;
    if (has_standardint32()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->standardint32());
    }

    // optional string someText = 3;
    if (has_sometext()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sometext());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Textmessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Textmessage*>(&from));
}

void Textmessage::MergeFrom(const Textmessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_longint64()) {
      set_longint64(from.longint64());
    }
    if (from.has_standardint32()) {
      set_standardint32(from.standardint32());
    }
    if (from.has_sometext()) {
      set_sometext(from.sometext());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void Textmessage::CopyFrom(const Textmessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Textmessage::IsInitialized() const {

  return true;
}

void Textmessage::Swap(Textmessage* other) {
  if (other != this) {
    std::swap(longint64_, other->longint64_);
    std::swap(standardint32_, other->standardint32_);
    std::swap(sometext_, other->sometext_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string Textmessage::GetTypeName() const {
  return "test.protobuf.Textmessage";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace test

// @@protoc_insertion_point(global_scope)
